import pandas as pd
import os

# --- CONFIGURATION ---
# The file generated by your 'Stocks_From_Trendlyne.py'
INPUT_FILE = "index.html" 
# The final file you want to upload to GitHub (can be the same to overwrite)
OUTPUT_FILE = "index.html" 

def categorize_stock(row):
    """
    Logic:
    1. Quality (Durability) + Technicals (Momentum) -> Top Priority
    2. Value (Valuation) -> Second Priority
    3. Everything else -> Third
    """
    # Thresholds (Adjust these if you want strict/loose filtering)
    GOOD_SCORE = 50 
    
    # Check if columns exist (handles cases where data might be missing)
    durability = row.get('Durability Score', 0)
    momentum = row.get('Momentum Score', 0)
    valuation = row.get('Valuation Score', 0)

    # TIER 1: Quality + Technicals
    if durability > GOOD_SCORE and momentum > GOOD_SCORE:
        return 1
    # TIER 2: Value
    elif valuation > GOOD_SCORE:
        return 2
    # TIER 3: Rest
    else:
        return 3

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Could not find {INPUT_FILE}. Run Stocks_From_Trendlyne.py first.")
        return

    print(f"Reading {INPUT_FILE}...")
    
    # Read HTML tables
    try:
        dfs = pd.read_html(INPUT_FILE)
        df = dfs[0] # Assuming the data is in the first table
    except ValueError:
        print("No tables found in the HTML file.")
        return

    # 1. CLEANUP: Ensure numeric columns are actually numbers
    score_cols = ['Durability Score', 'Valuation Score', 'Momentum Score']
    for col in score_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

    # 2. CALCULATE: Average Score (if not already there)
    if 'Average Score' not in df.columns:
        # Check which of the 3 columns actually exist in the file
        available_cols = [c for c in score_cols if c in df.columns]
        if available_cols:
            df['Average Score'] = df[available_cols].mean(axis=1).round(2)
        else:
            df['Average Score'] = 0

    # 3. SEGREGATE: Apply the tier logic
    # We create a temporary column 'Rank_Tier' to help with sorting
    df['Rank_Tier'] = df.apply(categorize_stock, axis=1)

    # 4. SORTING
    # Primary Sort: Rank_Tier (Ascending: 1, then 2, then 3)
    # Secondary Sort: Average Score (Descending: Highest first)
    df = df.sort_values(by=['Rank_Tier', 'Average Score'], ascending=[True, False])

    # 5. FORMATTING
    # Optional: Add a text label for the section
    tier_map = {
        1: "🔥 Quality + Technicals",
        2: "💰 High Value",
        3: "⚠️ Neutral / Others"
    }
    df['Category'] = df['Rank_Tier'].map(tier_map)

    # Reorder columns: Put 'Category' and 'Average Score' at the start
    cols = list(df.columns)
    # Move Category to index 0
    if 'Category' in cols: 
        cols.insert(0, cols.pop(cols.index('Category')))
    # Move Average Score to index 1
    if 'Average Score' in cols: 
        cols.insert(1, cols.pop(cols.index('Average Score')))
    
    # Remove the helper column 'Rank_Tier' before saving
    final_df = df[cols].drop(columns=['Rank_Tier'])

    # 6. SAVE
    # We use 'escape=False' so if you have links in the table, they remain clickable
    print(f"Sorting complete. Saving to {OUTPUT_FILE}...")
    final_df.to_html(OUTPUT_FILE, index=False, escape=False, border=1)
    print("Done!")

if __name__ == "__main__":
    main()
